### ISSUE TITLE
sessionid yang sudah pernah dipakai tidak bisa konek ulang

### ISSUE THREAD

**Issue by saifulcoder** [ookamiiixd/baileys-api#163]
mas saya ada kendala
saya add session dengan sessionid yang sudah pernah dipakai tapi tidak bisa scan ulang di aplikasi whatsapp gagal ada keterangan harus logout dulu. padahal sudah delete session
tapi misal dengan sessionid yang baru, scan qr berhasil

ini keterangan di api nya

`{"level":50,"time":1678504155219,"pid":4776,"hostname":"WIN-93U67GR3CJG","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
{"level":50,"time":1678504155222,"pid":4776,"hostname":"WIN-93U67GR3CJG","err":{"type":"Error","message":"Connection Closed","stack":"Error: Connection Closed\n    at sendRawMessage 
(D:\\laragon\\www\\github-laravel-wa-server\\backend\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:50:19)\n    at sendNode (D:\\laragon\\www\\github-laravel-wa-server\\backend\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:61:16)\n    at Object.logout (D:\\laragon\\www\\github-laravel-wa-server\\backend\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:328:19)\n    at destroy (D:\\laragon\\www\\github-laravel-wa-server\\backend\\dist\\wa.js:81:34)\n    at handleConnectionClose (D:\\laragon\\www\\github-laravel-wa-server\\backend\\dist\\wa.js:106:13)\n    at EventEmitter.<anonymous> (D:\\laragon\\www\\github-laravel-wa-server\\backend\\dist\\wa.js:175:13)\n    at EventEmitter.emit (node:events:538:35)\n    at EventEmitter.<anonymous> (D:\\laragon\\www\\github-laravel-wa-server\\backend\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\event-buffer.js:40:16)\n    at EventEmitter.emit (node:events:526:28)\n    at Object.emit (D:\\laragon\\www\\github-laravel-wa-server\\backend\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\event-buffer.js:94:23)","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Closed"},"headers":{}}},"msg":"An error occured during session destroy"}`

**Comment by mdestafadilah** [comment]
coba session dari installan baileys foldernya hapus semua, dan whatsapp yang mau di linked/ pairing dihapus, terus masukin lagi nomor yang sama dari whatsapp.

**Comment by ookamiiixd** [comment]
Ini rare case sih, setelah versi terbaru rilis, silahkan dicoba lagi. Kalau masih sama, asumsi saya adalah adanya race condition di sisi masnya

**Comment by mdestafadilah** [comment]
> Ini rare case sih, setelah versi terbaru rilis, silahkan dicoba lagi. Kalau masih sama, asumsi saya adalah adanya race condition di sisi masnya

hayo pak, kembangin lagi hehe

**Comment by ookamiiixd** [comment]
> > Ini rare case sih, setelah versi terbaru rilis, silahkan dicoba lagi. Kalau masih sama, asumsi saya adalah adanya race condition di sisi masnya
> 
> hayo pak, kembangin lagi hehe

Haha iya, akhirnya saya ada waktu buat ngerjain project ini. Ini lagi proses rewrite ulang dengan harapan kodenya lebih maintainable

**Comment by mdestafadilah** [comment]
> > > Ini rare case sih, setelah versi terbaru rilis, silahkan dicoba lagi. Kalau masih sama, asumsi saya adalah adanya race condition di sisi masnya
> > 
> > 
> > hayo pak, kembangin lagi hehe
> 
> Haha iya, akhirnya saya ada waktu buat ngerjain project ini. Ini lagi proses rewrite ulang dengan harapan kodenya lebih maintainable

mantapp, migrasi pake hono pak... sy tengok bbrp api serupa pakai hono ..
