### ISSUE TITLE
Error after scanning QR code (No Seassion Found)

### ISSUE THREAD

**Issue by Shalikoo** [ookamiiixd/baileys-api#170]
I am trying to install the latest version for the first time and I keep recieving the error 

`{"level":50,"time":1680105375263,"pid":23628,"hostname":"ShalevPC","err":{"type":"NotFoundError","message":"No Session found","stack":"NotFoundError: No Session found\n    at C:\\Users\\ShalevPC\\Downloads\\baileys-api-master\\baileys-api-master\\node_modules\\@prisma\\client\\runtime\\index.js:34062:15\n    at async C:\\Users\\ShalevPC\\Downloads\\baileys-api-master\\baileys-api-master\\node_modules\\@prisma\\client\\runtime\\index.js:34060:20\n    at async read (C:\\Users\\ShalevPC\\Downloads\\baileys-api-master\\baileys-api-master\\node_modules\\@ookamiiixd\\baileys-store\\dist\\session.js:28:30)\n    at async useSession (C:\\Users\\ShalevPC\\Downloads\\baileys-api-master\\baileys-api-master\\node_modules\\@ookamiiixd\\baileys-store\\dist\\session.js:50:20)\n    at async createSession (C:\\Users\\ShalevPC\\Downloads\\baileys-api-master\\baileys-api-master\\src\\wa.ts:145:32)","code":"P2025","clientVersion":"4.7.1","name":"NotFoundError"},"msg":"An error occured during session read"}`

the session data is instered to db and also messages but I keep getting this like its cant do anything .

**Comment by Fonnte** [comment]
This happen on latest baileys update due to updating signal. If you wanna get rid of this, try to use npm version until further update from adi.
