### ISSUE TITLE
Error when send a messge

### ISSUE THREAD

**Issue by sostenesapollo** [ookamiiixd/baileys-api#171]
"level":50,"time":1680156516763,"pid":23490,"hostname":"sostenes.local","err":{"type":"PrismaClientKnownRequestError","message":"\nInvalid `model.create()` invocation in\n/Users/sostenesapollo/dev/apollotecx/stockyzeit/whatsapp-api/node_modules/@ookamiiixd/baileys-store/dist/handlers/message.js:79:27\n\n  76         },\n  77     },\n  78 }),\n→ 79 model.create(\nUnique constraint failed on the constraint: `PRIMARY`","stack":"Error: \nInvalid `model.create()` invocation in\n/Users/sostenesapollo/dev/apollotecx/stockyzeit/whatsapp-api/node_modules/@ookamiiixd/baileys-store/dist/handlers/message.js:79:27\n\n  76         },\n  77     },\n  78 }),\n→ 79 model.create(\nUnique constraint failed on the constraint: `PRIMARY`\n    at fn.handleRequestError (/Users/sostenesapollo/dev/apollotecx/stockyzeit/whatsapp-api/node_modules/@prisma/client/runtime/library.js:174:6477)\n    at fn.handleAndLogRequestError (/Users/sostenesapollo/dev/apollotecx/stockyzeit/whatsapp-api/node_modules/@prisma/client/runtime/library.js:174:5907)\n    at fn.request (/Users/sostenesapollo/dev/apollotecx/stockyzeit/whatsapp-api/node_modules/@prisma/client/runtime/library.js:174:5786)\n    at async t._request (/Users/sostenesapollo/dev/apollotecx/stockyzeit/whatsapp-api/node_modules/@prisma/client/runtime/library.js:177:10477)\n    at async Promise.all (index 1)\n    at async EventEmitter.update (/Users/sostenesapollo/dev/apollotecx/stockyzeit/whatsapp-api/node_modules/@ookamiiixd/baileys-store/dist/handlers/message.js:68:17)","code":"P2002","clientVersion":"4.12.0","meta":{"target":"PRIMARY"}},"msg":"An error occured during message update"}

**Comment by microprocessgit** [comment]
I'm getting the same message.
