### ISSUE TITLE
Cannot find module '@adiwajshing/keyed-db'

### ISSUE THREAD

**Issue by ilhamsk4** [ookamiiixd/baileys-api#28]
Server is listening on http://127.0.0.1:3000
(node:9028) UnhandledPromiseRejectionWarning: Error: Cannot find module '@adiwajshing/keyed-db'
Require stack:
- D:\PROGRAM\NODE JS\baileys-api\node_modules\@adiwajshing\baileys\lib\Store\make-in-memory-store.js
- D:\PROGRAM\NODE JS\baileys-api\node_modules\@adiwajshing\baileys\lib\Store\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at exports.default (D:\PROGRAM\NODE JS\baileys-api\node_modules\@adiwajshing\baileys\lib\Store\make-in-memory-store.js:23:21)
    at createSession (file:///D:/PROGRAM/NODE%20JS/baileys-api/whatsapp.js:52:19)
    at add (file:///D:/PROGRAM/NODE%20JS/baileys-api/controllers/sessionController.js:19:5)
    at Layer.handle [as handle_request] (D:\PROGRAM\NODE JS\baileys-api\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\PROGRAM\NODE JS\baileys-api\node_modules\express\lib\router\route.js:137:13)
    at validate (file:///D:/PROGRAM/NODE%20JS/baileys-api/middlewares/requestValidator.js:11:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ilhamsk4** [comment]
ini saya pas create session baru gini

**Comment by saifulcoder** [comment]
`npm i @adiwajshing/keyed-db`

**Comment by ookamiiixd** [comment]
Solved @ilhamsk4 ?
