### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by aarvee022** [ookamiiixd/baileys-api#42]
Hi,

I have added function to read messages in whatsapp.js

wa.ev.on('messages.upsert', async ({ messages }) => {
    const m = messages[0]
    const messageType = Object.keys (m.message)[0]

I am getting following error on message on messageType

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at EventEmitter.<anonymous> (file:///C:/baileys-new/whatsapp.js:103:32)
    at EventEmitter.emit (node:events:532:35)
    at C:\baileys-new\node_modules\@adiwajshing\baileys\lib\Socket\messages-recv.js:393:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Running cleanup before exit.

Please Help

**Comment by vyxxr** [comment]
try this

```
wa.ev.on('messages.upsert', async (m) => {
    const message = m.messages[0]
    const messageType = Object.keys(message.message)[0]
```

**Comment by ookamiiixd** [comment]
The solution provided by @vyxxr should do it.

**Comment by ookamiiixd** [comment]
Since OP didn't reply to this issue after a while, i suppose this has been solved, closing this.

**Comment by aarvee022** [comment]
sorry that was different error it has been resolved

**Comment by aarvee022** [comment]
Still getting errors

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at EventEmitter.<anonymous> (file:///C:/baileys-new/whatsapp.js:102:32)
    at EventEmitter.emit (node:events:532:35)
    at C:\baileys-new\node_modules\@adiwajshing\baileys\lib\Socket\messages-recv.js:393:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Running cleanup before exit.
