### ISSUE TITLE
Send image error

### ISSUE THREAD

**Issue by mywidget** [ookamiiixd/baileys-api#53]
`SyntaxError: Unexpected token r in JSON at position 7
    at JSON.parse (<anonymous>)
    at parse (E:\Ampps\www\baileys-api\node_modules\body-parser\lib\types\json.js:89:19)
    at E:\Ampps\www\baileys-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (E:\Ampps\www\baileys-api\node_modules\raw-body\index.js:224:16)
    at done (E:\Ampps\www\baileys-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (E:\Ampps\www\baileys-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

**Comment by ookamiiixd** [comment]
Probably you sent an invalid request body. How is your request looks like?
