### ISSUE TITLE
Create New Session in python

### ISSUE THREAD

**Issue by gabrielnm123** [ookamiiixd/baileys-api#90]
Code i used:

```
import requests

url = "http://localhost:8000/sessions/add"
payload='id=john&isLegacy=false'
headers = {'Content-Type': 'application/json'}
response = requests.request("POST", url, headers=headers, data=payload)
print(response.text)

```
When running:

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token i in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (/home/gabriel/GitHub/baileys-api/node_modules/body-parser/lib/types/json.js:160:10)<br> &nbsp; &nbsp;at parse (/home/gabriel/GitHub/baileys-api/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /home/gabriel/GitHub/baileys-api/node_modules/body-parser/lib/read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (async_hooks.js:197:9)<br> &nbsp; &nbsp;at invokeCallback (/home/gabriel/GitHub/baileys-api/node_modules/raw-body/index.js:231:16)<br> &nbsp; &nbsp;at done (/home/gabriel/GitHub/baileys-api/node_modules/raw-body/index.js:220:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/gabriel/GitHub/baileys-api/node_modules/raw-body/index.js:280:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:412:35)<br> &nbsp; &nbsp;at endReadableNT (internal/streams/readable.js:1333:12)</pre>
</body>
</html>

**Comment by gabrielnm123** [comment]
I just changed headers = {'Content-Type': 'application/x-www-form-urlencoded'}
